openapi: 3.0.1
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/FRodrigues42/CodeChallengeJava/0.0.1
  - url: 'http://localhost:8080/api'
    description: Development server
info:
  version: '0.0.1'
  title: CodeChallengeJava
  contact:
    email: mail@frodrigues.info
tags:
  - name: 'Main Exercise'
    description: 'The purposed required exercise'
  - name: 'Optional'
    description: 'Optional exercise'
paths:
  /difference:
    summary: >-
      Service that calculates the difference between the sum of the squares of
      the N natural numbers and the square of the sum of the same numbers
    get:
      summary: >-
        Get the difference between the sum of the squares of the N natural
        numbers and the square of the sum of the same numbers
      description: ''
      operationId: getDifference
      parameters:
        - name: 'number'
          in: 'query'
          description: 'Number for the first N natural numbers'
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: 'Successful calculation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Difference'
              examples:
                '10':
                  value:
                    datetime: '2021-08-09T00:45:24.413977+01:00'
                    value: 2640
                    number: 10
                    occurrences: 1
        '400':
          description: >-
            Invalid number (must be greater than 0 and less or equal to 100)
      tags:
        - Main Exercise
components:
  responses:
    Problem:
      description: >-
        error occurred - see status code and problem object for more
        information.
      content:
        application/problem+json:
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
  schemas:
    Difference:
      type: object
      properties:
        datetime:
          type: string
          format: date-time
        value:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        occurrences:
          type: integer
          format: int64
security:
  - jwt: []
  - basic: []
