openapi: 3.0.1
info:
  title: CodeChallengeJava
  contact:
    email: mail@frodrigues.info
  version: 0.0.1
servers:
- url: https://virtserver.swaggerhub.com/FRodrigues42/CodeChallengeJava/0.0.1
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080/api
  description: Development server
security:
- jwt: []
- basic: []
tags:
- name: Main Exercise
  description: The purposed required exercise
- name: Optional
  description: Optional exercise
paths:
  /difference:
    summary: 'Service that calculates the difference between the sum of the squares
      of the N natural numbers and the square of the sum of the same numbers '
    get:
      tags:
      - Main Exercise
      summary: 'Get the difference between the sum of the squares of the N natural
        numbers and the square of the sum of the same numbers '
      operationId: getDifference
      parameters:
      - name: number
        in: query
        description: Number for the first N natural numbers
        required: true
        style: form
        explode: true
        schema:
          maximum: 100
          minimum: 1
          type: integer
          format: int64
      responses:
        "200":
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Difference'
              examples:
                "10":
                  value:
                    datetime: 2021-08-09T00:45:24.413977
                    value: 2640
                    number: 10
                    occurrences: 1
        "400":
          description: Invalid number (must be greater than 0 and less or equal to
            100)
components:
  schemas:
    Difference:
      type: object
      properties:
        datetime:
          type: string
          format: date-time
        value:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        occurrences:
          type: integer
          format: int64
    Problem:
      type: object
      properties:
        type:
          type: string
          description: "An absolute URI that identifies the problem type.  When dereferenced,\n\
            it SHOULD provide human-readable documentation for the problem type\n\
            (e.g., using HTML).\n"
          format: uri
          example: https://zalando.github.io/problem/constraint-violation
          default: about:blank
        title:
          type: string
          description: "A short, summary of the problem type. Written in english and\
            \ readable\nfor engineers (usually not suited for non technical stakeholders\
            \ and\nnot localized); example: Service Unavailable\n"
        status:
          maximum: 600
          exclusiveMaximum: true
          minimum: 100
          type: integer
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          format: int32
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
